training_params:
  metric_mode: "max"
  loss_function: []

  lr: 0.0001
  batch_size: 4
  decay: 0.0005
  patience: 5
  start_epoch: 0
  epochs: 21
  workers: 4
  seed: 42
  image_size: 512
  is_augmentation: True
  lr_scheduler: "OneCycleLR"
  alpha: 0.25
  gamma: 2.0